AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Rakefile'
    - 'Guardfile'
    - 'Gemfile'

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20
